### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by Vlyn** [Rojetto/ReNeo#1]
Hey,

wollte es nur nochmal anbringen wegen "Tray Icon (braucht man das tatsächlich?)".

Ich benutze NEO2 mit kbdneo und dem AHK Skript seit ca. 10 Jahren. Das große Problem dabei (abgesehen davon, dass das Skript teils hängen bleibt und in GTK Programme nichts funktioniert): Spiele kicken oder bannen einen für AHK Skripte. Heißt ich habe mir angewohnt das Skript immer zu beenden bevor ich ein Multiplayer-Spiel starte.

Daher wäre ein Tray-Icon super, macht es auch viel einfacher ReNeo zu deaktivieren oder zu beenden. Und man vergisst nicht so einfach darauf, dass es evtl. gerade läuft.

Da sich ReNeo beim Keyboard einklickt ist hier sicher auch die Gefahr gegeben, dass es evtl. als Cheat angesehen wird?

**Comment by Rojetto** [comment]
Danke für dein Feedback. Das Thema mit den Spielen war bei mir noch nicht aufgekommen, gebe dir Recht dass es dafür nützlich wäre. 

Prinzipiell kann ich nicht ausschließen dass ReNeo auch als Cheat erkannt wird. Kommt darauf an, wie die Analyse des Spiels funktioniert, aber grundlegend hookt ReNeo die Tastatur genau so wie auch AHK.

**Comment by qwertfisch** [comment]
Man könnte alternativ einen Shortcut einbauen zum De/Aktivieren. Bei NeoVars ist dies Shift+Pause. In der Regel nutzt kein anderes Programm diesen. Mir würde allerdings die mangelnde Rückmeldung etwas fehlen. Das Problem existierte bereits mit dem alten Layout-Wechsel über z.B. Alt+Shift.

Kann man einen Ballontip ausgeben ohne Trayicon?

**Comment by Vlyn** [comment]
Ein Trayicon wäre besser (evtl. mit Möglichkeit das auszublenden). Man will ja auf einen Blick sehen ob alles läuft (Z.B. nach dem Windows Restart gibt es auch gerne mal Probleme, dass das AHK Script nicht ordentlich startet). Dann kann es auch mit Doppelklick schnell deaktiviert werden (wenn man auf QWERTZ wechselt, oft, weil jemand anderer kurz an den Computer muss).

**Comment by Rojetto** [comment]
Für den schnellen Wechsel zu QWERTZ gibt es ja schon nativ Strg+Shift, mit Feedback über die Sprachleiste (wenn man QWERTZ installiert hat). Daher würde ich gerne ReNeo möglichst weit im Hintergrund halten und keinen Shortcut mit sehr ähnlicher Funktion einführen. Ballontips ohne Trayicon gehen nach meiner Erfahrung nicht. Außerdem finde ich das Benachrichtigungssystem in Windows 10 sowieso unangenehm aufdringlich und hakelig, und möchte es deshalb wenn es geht umschiffen.

Ein einfaches Trayicon mit den Funktionen
- Aktivierungsstatus anzeigen
- Keyboard-Hook (de)aktivieren
- ReNeo beenden

gefällt mir insgesamt am besten.

**Comment by qwertfisch** [comment]
Die systeminternen Shortcuts zum Layoutwechseln erfüllen den Zweck im Zusammenspiel mit der automatischen Deaktivierung bei „falschem“ Layout. Das ist insofern ein Vorteil gegenüber NeoVars, welches einen eigenen Shortcut dafür benötigt.

Dennoch soll es eine zusätzliche Tray-Funktion „(de)aktivieren“ geben, die anscheinend unabhängig vom gerade aktiven Layout ist. Soll in dem Fall der Keyboard-Hook komplett entfernt (bzw. hinzugefügt) werden, oder soll lediglich am Anfang des Hooks geprüft werden, ob man aktiv ist (so wie es jetzt mit dem Layout-Check gemacht wird)? Ich vermute letzteres reicht aus, um keine Anticheat-Maßnahmen auszulösen, da keine Fake-Tastendrücke erzeugt werden.

**Comment by Vlyn** [comment]
Ich finde generell ein automatisches An- und Abschalten eine schlechte Idee, das bräuchte wieder einen Hook zum aktuellen Windows Tastaturlayout. Hier gibt es aber NEO2, Bone und einige andere Varianten (Evtl. auch modifizierte).

ReNeo sollte unabhängig sein, entweder man schaltet es an oder aus. War bei NEO2 auch nie anders, wechselt man z.B. auf QWERTZ (Win + Leertaste) macht man eben einen schnellen Doppelklick auf das Tray Icon. Wenn überhaupt nötig (QWERTZ funktioniert normalerweise auch mit dem Erweiterungsskript in den meisten Fällen problemlos, wenn man z.B. nur kurzfristig umschaltet).

So eine Automatik finde ich zu gefährlich und fehleranfällig.

**Comment by qwertfisch** [comment]
> So eine Automatik finde ich zu gefährlich und fehleranfällig.

Das automatische An/Abschalten ist doch bereits umgesetzt. Bei kbdneo gab es das zwar bisher nicht, aber das Zusatzskript hatte dort auch viel weniger Aufgaben übernommen als ReNeo. Was an der Automatik hältst Du für gefährlich / fehleranfällig?

> Ich finde generell ein automatisches An- und Abschalten eine schlechte Idee, das bräuchte wieder einen Hook zum aktuellen Windows Tastaturlayout. Hier gibt es aber NEO2, Bone und einige andere Varianten (Evtl. auch modifizierte).

Das erfordert keinen Keyboard-Hook. Es wird lediglich auf die drei möglichen aktiven Layouts (aktuell hartkodiert) geprüft, welches aktiv ist nach einem Fenster/Programmwechsel. Dass die eigentliche Deaktivierung aktuell noch im Keyboardhook am Anfang stattfindet, ist technisch nicht notwendig und könnte auch an anderer Stelle erfolgen, bspw. beim Hook für die Prüfung des Fensterwechsels. Dann ließe sich auch der Keyboard-Hook komplett abschalten / neu einrichten.

Wie gesagt ,ich weiß nicht, ob es notwendig für die Anticheat-Maßnahmen ist, den Hook komplett rauszunehmen oder lediglich die Erzeugung falscher Tastendrücke zu unterbinden. Das ist dann auch die Frage bei der Umsetzung der manuellen Deaktivierung (über das Traysymbol).

**Comment by Rojetto** [comment]
> Dennoch wird eine zusätzliche Tray-Funktion „(de)aktivieren“ vorgeschlagen, die anscheinend unabhängig vom gerade aktiven Layout ist. Soll in dem Fall der Keyboard-Hook komplett entfernt (bzw. hinzugefügt) werden, oder soll lediglich am Anfang des Hooks geprüft werden, ob man aktiv ist (so wie es jetzt mit dem Layout-Check gemacht wird)?

Würde sagen wenn, dann richtig. Wenn man den Hook komplett entfernt ist man auf der sicheren Seite.

> So eine Automatik finde ich zu gefährlich und fehleranfällig.

In meiner jetzigen Vorstellung gibt es zwei Varianten von „deaktiviert“:
1. ReNeo läuft grundsätzlich, macht aber nix weil das Tastaturlayout nicht passt. So funktioniert es gerade auch schon.
2. ReNeo wurde über das Trayicon komplett inert geschaltet und lässt sich auch nur so wieder aktivieren. Das müsste noch implementiert werden.

Variante 1 möchte ich auf keinen Fall verlieren. Die benutze ich täglich und finde es gut, dass man ReNeo im Prinzip komplett vergessen kann, ich wechsel halt in Windows das Layout, so wie ich es immer mache.
Variante 2 sollte deinen Anwendungsfall abdecken.

> Dass die eigentliche Deaktivierung aktuell noch im Keyboardhook am Anfang stattfindet, ist technisch nicht notwendig und könnte auch an anderer Stelle erfolgen, bspw. beim Hook für die Prüfung des Fensterwechsels.

Völlig richtig, das ist eine etwas seltsame Krücke. Tatsächlich war es aber bisher die robusteste Variante, die ich gefunden habe. Angeblich gibt es irgendwelche COM-Events für den Layoutwechsel, die war es mir aber nicht gelungen anzuzapfen. Bei jedem Tastenanschlag die Registry auszulesen (was man machen muss, um die DLL herauszufinden) fand ich auch nicht gut. Das Fensterwechsel-Event hingegen wird unter anderem auch dann gefeuert, wenn mit Win+Leertaste das Menü der Sprachleiste aufgeht. Komischerweise ist das Layout was man ausliest aber noch nicht korrekt, in dem Moment in dem man zurück ins ursprüngliche Fenster wechselt, das scheint erst später im Eventablauf geändert zu werden? Deshalb gibt es jetzt diese eigenartige Lösung.

**Comment by qwertfisch** [comment]
Hört sich sinnvoll an mit den zwei unterschiedlichen Varianten einer Deaktivierung. Das lässt sich relativ einfach umsetzen. Ich habe mich vorgestern etwas umgesehen im Code und mit D beschäftigt. Wenn du nicht schon mit der Umsetzung begonnen hast, würde ich mich gerne an dieser Aufgabe versuchen (hätte ab nächster Woche Zeit dafür).

Als Trayicon lässt sich das übliche Neo-Icon verwenden.

**Comment by Rojetto** [comment]
Habe selber noch nicht angefangen. Das kannst du sehr gerne probieren 👍
