### ISSUE TITLE
Ebene 4 Steuertasten gehen nicht im Terminal

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#11]
Pfeiltasten, Enter, Tab auf Ebene 4 funktionieren alle nicht im Terminal. Getestet in ConEmu und dem alten Windows Terminal. In der neuen Terminal App geht's.

**Comment by qwertfisch** [comment]
In `cmd.exe` unter Windows 7 funktionieren die genannten Tasten.

**Comment by Rojetto** [comment]
Interessant. Habe es gerade selber nochmal ausprobiert (Windows 10), und mit komischen Kombinationen aus Fenster wechseln und zwischen QWERTZ und Neo wechseln hat es jetzt manchmal geklappt, so lange bis ich wieder in ein anderes Fenster und zurück gehe. Vielleicht fummelt das Terminal selber irgendwie an der Eingabemethode rum oder so?

**Comment by Rojetto** [comment]
Workaround in [v1.4.3](https://github.com/Rojetto/ReNeo/releases/tag/v1.4.3) behält vorherige Layouteinstellung bei, wenn man ins Terminal wechselt. Damit sollte es fast immer wie erwartet funktionieren. Nur wenn man *im* Terminal das Layout wechselt, bekommt ReNeo das nicht mit, das scheint aber die Win32-API nicht wirklich herzugeben.
