### ISSUE TITLE
Standalone is working fine, Extension mode is not

### ISSUE THREAD

**Issue by Ro4cHii** [Rojetto/ReNeo#112]
Hello all,

just recently I stumbled upon Neo and I am really loving it so far.

On my work computer, I installed kbdnoted and run ReNeo in extension mode - everything is working just fine.

On my personal computer however, I just cannot seem to get the extension mode to run properly.
I tried multiple un-/reinstalls and made sure to follow the installation guide exactly.

The layout is working fine, but the extension features (e. g. arrow keys on MOD4) are not working at all.
Also, I cannot activate the OSK (shortcut or context menu - no difference). It just doesn't pop up.

Here is my config:
```
{
    "autoNumlock": true,
    "blacklist": [],
    "enableMod4Lock": true,
    "filterNeoModifiers": true,
    "hotkeys": {
        "toggleActivation": "Ctrl+Shift+Key_N",
        "toggleOSK": null,
        "toggleOneHandedMode": null
    },
    "language": "german",
    "oneHandedMode": {
        "mirrorKey": "39",
        "mirrorMap": {
            "02": "0B",
            "03": "0A",
            "04": "09",
            "05": "08",
            "06": "07",
            "07": "06",
            "08": "05",
            "09": "04",
            "0A": "03",
            "0B": "0C",
            "0F": "1A",
            "10": "19",
            "11": "18",
            "12": "17",
            "13": "16",
            "14": "15",
            "15": "14",
            "16": "13",
            "17": "12",
            "18": "11",
            "19": "10",
            "1A": "0F",
            "1E": "27",
            "1F": "26",
            "20": "25",
            "21": "24",
            "22": "23",
            "23": "22",
            "24": "21",
            "25": "20",
            "26": "1F",
            "27": "1E",
            "2C": "35",
            "2D": "34",
            "2E": "33",
            "2F": "32",
            "30": "31",
            "31": "30",
            "32": "2F",
            "33": "2E",
            "34": "2D",
            "35": "2C",
            "3A": "28"
        }
    },
    "osk": {
        "layout": "iso",
        "modifierNames": "standard",
        "numberRow": true,
        "numpad": false,
        "theme": "ColorClassic"
    },
    "standaloneLayout": "Noted",
    "standaloneMode": false
}
```

With `standaloneMode": true` all is working well. Setting the value to _false_ results in the described behavior (opposed to my work computer where everything is working just fine).
I have even tried to run ReNeo on startup in admin mode - also no difference.
Unfortunately, I am a heavy AutoHotkey user so I cannot rely on ReNeo alone but instead need the native functionality of kbdneo.

I also tried to run the debug exe but the log does not seem to be really helpful.
[reneo_log.txt](https://github.com/user-attachments/files/16822177/reneo_log.txt)

Any ideas? :(

**Comment by Ro4cHii** [comment]
Update: I don't know what happened but now it is also not working on my work computer anymore :(

I am 100% certain that I had it working in extension mode before and now it just doesn't. This is really frustrating.

The debug exe doesn't help at all here. How can I proceed to narrow down the error?

**Comment by Ro4cHii** [comment]
Anyone? :(

**Comment by reminiscience** [comment]
Having the same problem. It might be related to the Noted layout. Even **Win + .** (to open the emoji keyboard) isn’t working with kbdnoted and ReNeo, only with standard German layout and ReNeo in standalone mode.

EDIT: I _think_ I’ve found the problem:
Just add the following line for the Noted layout in **layouts.json**:

`"dllName": "kbdnoted.dll",`

… directly under

`"name": "Noted",`

**Comment by Ro4cHii** [comment]
> EDIT: I _think_ I’ve found the problem: Just add the following line for the Noted layout in **layouts.json**:
> `"dllName": "kbdnoted.dll",`
> … directly under
> `"name": "Noted",`

You're my hero – thank you so much! :)

**Comment by Rsge** [comment]
@Ro4cHii Maybe you could reopen this issue until the fix by @reminiscience is actually added in the main repo, so it’s easier to find and the author sees that they still could do something to fix it for good.
