### ISSUE TITLE
Was senden wir für Scancodes und wie funktionieren Sonderzeichen?

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#20]
### Sonderzeichen

Im Erweiterungsmodus senden wir gerade für Sonderzeichen direkt VK_PACKETs. Zur Texteingabe geht das gut, möglicherweise gibt es damit aber nicht 100% Kompatibilität. In Gimp beispielsweise kann ich mit # nicht mehr das Gitter ein- und ausschalten. NeoVars hingegen sendet die QWERTZ-äquivalenten Tastenkombinationen, also z. B. Strg+Alt+Q für @. Die lassen sich auch mit [`VkKeyScanEx`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-vkkeyscanexa) herausbekommen. Damit ist man natürlich darauf angewiesen, dass das native Layout die entsprechenden Zeichen überhaupt hat. Im Erweiterungsmodus machen wir das gerade nicht, weil verschiedene Programme ja die Modifier für die oberen Ebenen falsch verstehen. Im Standalone Modus aufbauend auf QWERTZ könnte man es zumindest für die Zeichen, bei denen es geht, versuchen.

### Scancodes
Bisher senden wir immer Scancode 0. Bei VK_PACKETs erübrigt sich das eh, aber was ist mit den normalen Tasten und den Steuertasten auf Ebene 4. Bei 0 bleiben? Den tatsächlichen Scancode der gedrückten Taste senden? Den, der bei QWERTZ käme? Was ist mit Ebene 4 und dem widersprüchlichen Extended Bit für die Navigationstasten? Hier fehlen bisher die Informationen um zu sagen was davon am besten ist.

### Was würde NeoVars tun? 🙏 
NeoVars sendet die Scancodes der entsprechenden Tasten so wie sie in QWERTZ kämen. Ein „w“ in Neo wird also durch ein VK_W mit Scancode 0x11 manifestiert. Für Sonderzeichen wählt NeoVars auch (wenn möglich) die Tastenkombination, die man in QWERTZ drücken müsste. Das hat jahrelang funktioniert, gerade habe ich festgestellt, dass Sonderzeichen durch Tastenkombinationen zu senden doch nicht ganz optimal ist. Wenn ich mit NeoVars in VS Code `//` eingebe öffnet sich die Befehlsleiste (die ist auf Doppel-Shift gemappt). Das wollen wir natürlich nicht...

### Vorschlag
Wir bieten zwei Optionen, zwischen denen man in `config.json` umschalten kann:
1. (Standard) Sonderzeichen werden einfach als VK_PACKET gesendet. Für andere VKs senden wir als Scancode den der tatsächlich gedrückten Taste.
2. Fake-Qwertz: Wenn möglich senden wir Sonderzeichen als Tastenkombination des aktuellen Layouts (wahrscheinlich QWERTZ), ansonsten als VK_PACKET. Für andere VKs (hauptsächlich Ebene 4) senden wir als Scancode die Taste des „echten“ Layouts, das in Windows ausgewählt ist.

**Comment by qwertfisch** [comment]
Ich kann nicht unbedingt abschätzen, welche Vor/Nachteile sich aus dem Senden von Scancodes oder Virtual Key Codes ergibt. Aktuell werden die Virtual Keys mit Scancode 0 gesendet (für normale Zeichen/Tasten), wenn ich das richtig sehe.

Option 1 hört sich gerade komisch an. Wenn ich ein Neo-X tippe, würde also der Scancode der Qwertz-Q-Taste gesendet (aber ein VK_X)?
Option 2 klingt ok, wenn VkKeyScanX einem die Arbeit abnimmt. Ich müsste aber nochmal nachschauen, was NeoVars tatsächlich macht / sendet, um mir ein Urteil bilden zu können.
Wo ist denn Option 3, die den aktuellen Stand abbildet? Also Scancode 0 und den passenden Virtual Key senden, oder halt ein VK_PACKET für Sonderzeichen,

Um Vor/Nachteile zu beurteilen, sollten auch Programme wie VirtualBox oder DOSBox getestet werden, bei denen die Ausgabe und das Keylayout intern gesetzt wird. Meine Vermutung ist, dass diese die empfangenen Zeichen (über VK_PACKET) ignorieren und sich nur auf die Virtual Keys oder besser noch die Scancodes konzentrieren. Hier werde ich mal schauen, wie sich die Programme verhalten bei kbdneo und NeoVars.

**Comment by Rojetto** [comment]
Grundsätzlich sendet man immer VKs, die Frage ist nur, welchen Scancode man *zusätzlich* mit angibt (außer bei VK_PACKET, da wird der Teil der Datenstruktur für den Unicode-Codepoint genutzt).

Option 1 meine ich genau so wie du es beschrieben hast. Die Logik für mich ist, dass der VK die *Bedeutung* der Taste wiedergibt (den Buchstaben X), und der Scancode die *Position* (oben links auf der Tastatur). Deswegen bin ich auch der Meinung, dass Spiele zum Beispiel den Scancode auswerten sollten, und nicht den VK, weil es ja für eine komfortable Bedienung um die physische Position der Taste geht. Wie sehr das tatsächlich so in der Praxis funktioniert ist eine andere Frage.

Deine Option 3 wäre identisch zu Option 1, nur dass wir für den Scancode immer 0 angeben, statt etwas entfernt sinnvolles. Glaube nicht, dass das irgendwo besser wäre.

Die Rechercheideen klingen gut, bin gespannt auf die Ergebnisse 👍

**Comment by qwertfisch** [comment]
Habe jetzt mal selbst getestet, was verschiedene Programme erwarten bzw. verwenden.

- __DOSBox__ scheint hauptsächlich den Scancode (und den Shift/Alt/Ctrl-Status) zu verwenden, ignoriert aber `VK_PACKET`. Beim Standalone-ReNeo (mit Scancode 0x0) funktioniert folglich keine einzige Taste, beim aktuellen ReNeo gehen entsprechend die AltGr-Codes für `\{}[]@|~²` nicht (außerdem nicht die Qwertz-Akzenttasten T1 und T2).  

  NeoVars klappt prima durch dessen Qwertz-Simulation, und kbdneo alleine funktioniert bis auf die rechte Mod3-Taste, bei der komischerweise der Virtual Key (VK_OEM_102) den Ausschlag gibt, obwohl der Scancode dem `#` entspricht.
- __VirtualBox__ schafft es, sich vorzudrängeln und alle Tastencodes für sich abzufangen. Lediglich die Up-Codes werden an andere Programme weitergeleitet. Somit ist es hier egal, welchen Treiber oder Tool man verwendet.

Wie sich Option 1 auswirken wird (z.B. in der DOSBox), wäre mal interessant zu sehen. Die Debug-Ausgabe wird interessant, wenn man bspw. Scancode 0x11 (Qwertz-Q) mit VK_X sendet, und was verschiedene Inputwidgets in Windows dann daraus machen.

Die Fake-Qwertz-Option bietet augenscheinlich sehr viel Kompatiblität. NeoVars ändert Scancode wie Virtual Key passend um, dass es dem Basis-Layout entspricht. Das ist einerseits praktisch für Programme wie DOSBox und sicherlich auch andere Tools, die bestimmte gedrückte Tasten(folgen) erwarten (und deren Qwertz-Werte kennen), aber deckt nur den Qwertz-Bereich ab. Oder den des aktuell gewählten Layouts. Wenn `VkKeyScanEx` korrekte Rückgabewerte liefert, könnten wir das einbauen und somit ggf. mehr Kompatibilität bereitstellen. Oder weniger, siehe dein Beispiel in VS Code …

Man muss aber auch sagen, dass beispielsweise bei den AltGr-Zeichen wie `@` wirklich _sehr_ viele virtuelle Tastendrücke auftauchen (zusammen 14, davon 6 injected, statt zwei Down- und zwei Up-Events – bei Numpad auf E4 sind es sogar 16/8). Deswegen hakt NeoVars vermutlich auch bei schnellen Folgen in Spielen mit Capslock-, Shift- und Strg-Tasten bzw. stürzt gar ab. Ich gehe jedoch davon aus, dass unsere Implementierung weniger „Rauschen“ erzeugen würde.

Ich halte es auch für sinnvoll beide Optionen erstmal zu implementieren, und auch für beide Varianten (Erweiterung/Standalone). Wir können das hinterher konfigurierbar machen, oder die Optionen erweisen sich als gleichwertig.

**Comment by qwertfisch** [comment]
Bei näherer Überlegung steckt eigentlich noch mehr dahinter, denn die Vorgehensweise hängt von der jeweiligen Ebene ab. Shift ist ein „normaler“ Modifikator mit Auswirkungen seitens des Basislayouts, während Mod3 und Mod4 erfundene und in anderen Programmen unbekannte Mods sind. Ich bin mir auch nicht sicher, ob man nicht beide Optionen kombinieren sollte.

| Ebene | Umsetzung | Besonderheiten |
| --- | --- | --- |
| 1 | Original-Scancode senden | keine |
| 2 | Original-Scancode senden | keine, Shift ist gedrückt |
| 3 | wird zu VK_PACKET | Scancode entspricht Unicode |
|  | Fake-Qwertz-Tastendrücke | für Zeichen des Basislayouts im Standalone-Modus |
| 4 | Original-Ext-Scancodes bzw. Numpad-Codes | keine |
| Shift+4 | wie Ebene 4 | zusätzlich gedrückte Shift-Taste unabhängig von ReNeo |
| 5 | wird zu VK_PACKET | ausschließlich „höhere“ Sonderzeichen |
| 6 | wird zu VK_PACKET | ausschließlich „höhere“ Sonderzeichen |

Auf Ebenen 2 und 5 lässt NeoVars das Shift jeweils durch und auch stehen. Somit sind alle E5-Zeichen gleichzeitig auch Shift-Zeichen (aber eben über VK_PACKET). Hatte überlegt, ob man in E5 die Shifttaste temporär „entshiftet“ (mit up/down) vor dem Senden des Unicodes.

**Comment by Rojetto** [comment]
Habe die besprochenen zwei Ansätze implementiert. In der neuen Option `"sendKeyMode"` kann man zwischen `"honest"` und `"fakeNative"` wechseln. Die Implementierung klappert auch weniger, für dein Beispiel `@` kommen bei ein Mal drücken genau 6 Events, davon drei runter und drei hoch. Auch das Problem mit der Suchleiste in VS Code tritt nicht auf, offenbar waren das bei NeoVars einfach unnötig viele Anschläge.
