### ISSUE TITLE
Standalone-Layout im Traymenü auswählen

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#22]
Für den Standalone-Modus soll im Traymenü ein weiteres Untermenü hinzugefügt werden, mit dem man zwischen den verfügbaren Layouts wechseln kann. Diese Auswahl soll in einer Datei abgespeichert werden.

In `config.json` existiert bereits ein Eintrag `standaloneLayout` der beim Starten geladen wird. Dieser müsste entsprechen überschrieben werden. Problem: Wenn man die JSON-Datei komplett neu schreibt, gehen vermutlich die sorgfältigen Ausrichtungen in den Layouts verloren (in die der Nutzer möglicherweise Zeit gesteckt hat). Vielleicht sollte man zumindest die Layouts deshalb in eine separate `layouts.json` auslagern, vielleicht ist das aber auch überflüssig. Kann der Implementierer entscheiden 🤷

**Comment by qwertfisch** [comment]
Das Auswahlmenü habe ich implementiert. Es ist ausgegraut, wenn gerade kein Standalone-Modus aktiv ist. Eventuell kann man das Menü auch ganz weglassen, wenn `standaloneMode` in der Konfiguration auf `false` steht.

Die JSON-Konfiguration wird ruiniert, wenn man sie erneut abspeichert. Soll ich den neu gewählten Wert trotzdem persistieren und zusätzlich eine `layouts.json` benutzen, oder lässt man es ganz? Dann könnte der Nutzer sein Basislayout nur in der Konfiguration ändern.

**Comment by Rojetto** [comment]
Klasse, vielen Dank! Persistieren finde ich schon sinnvoll, ist auf jeden Fall was ich als Nutzer erwarten würde. Eine separate `layouts.json` ist dann mMn ein guter Kompromiss.
