### ISSUE TITLE
Backtick auf Neo Z(3) im Standalone-Modus mit fakeNative ist tot

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#26]
Konfiguration: Standalone-Modus, nativ QWERTZ, fakeNative

Backtick ` auf Neo Z(3) verhält sich wie eine tote Taste. Liegt daran, dass hier die native QWERTZ-Taste gesendet wird, die tot ist. Entweder man markiert diesen Sonderfall irgendwie im Mapping (betrifft evtl auch noch andere Sonderzeichen), oder man versucht herauszufinden, ob eine Taste im nativen Layout tot ist und vermeidet die dann (also sendet stattdessen das Unicode-Symbol).

Update: Betrifft auch Erweiterungsmodus mit fakeNative, da kbdneo eine Tottaste mit dem Zeichen hat

**Comment by qwertfisch** [comment]
Das Problem tritt zwar generell auch im Erweiterungsmodus auf, die Verwendung von `sendUTF16OrKeyCombo` ist dort aber unsinnig. Die weiteren Sonderzeichen bestehen nämlich aus Mod3-Kombinationen, die absichtlich durch Unicode-Packets ersetzt werden. Daher ist eine Fallunterscheidung besser, so dass man von vornherein Unicode sendet.

Im Standalone-Modus führen alle Tottasten zu dem Problem. Unter nativem Qwertz sind dies VK_OEM_5 und VK_OEM_6, respektive für `^` und `` ` ``. Ich habe eine Lösung mittels [MapVirtualKey](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyw) gefunden, welches (anscheinend ohne weitere Nachteile) ausgibt, ob ein VK eine Tottaste ist:
> __MAPVK_VK_TO_CHAR__ […] Dead keys (diacritics) are indicated by setting the top bit of the return value. 

Der PR dazu kommt morgen. Ich will noch etwas rumtesten mit französischem Layout (Azerty). Bin mir sicher, da finde ich noch Randfälle, die nicht funktionieren.

**Comment by Rojetto** [comment]
Klasse, die Funktion passt ja perfekt! Ja, eine vorherige Fallunterscheidung zwischen Standalone und Erweiterung ist sinnvoll.

**Comment by qwertfisch** [comment]
Leider werden damit nur tote Tasten abgedeckt, die keinen Modifier benötigen. Dies fällt z.B. im französischen Layout auf, welches die Akzente `~` und `` ` `` auf AltGr-2 bzw. AltGr-7 hat, bei denen MapVirtualKey (für die Zifferntasten) keinen Deadkey zurückgibt.

Ich habe es geschafft, mittels [ToUnicode](https://docs.microsoft.com/en-US/windows/win32/api/winuser/nf-winuser-tounicode) auch diese Tasten zu erkennen, allerdings weiß ich nicht, wieviel aufwendiger der Aufruf ist. Sollte aber ähnlich sein wie MapVirtualKey. Die Funktion benötigt zwar einen vollständigen Keyboard State, aber diesen kann man vermutlich (noch zu testen!) auch selbst generieren statt ihn über [GetKeyboardState](https://docs.microsoft.com/en-US/windows/win32/api/winuser/nf-winuser-getkeyboardstate) abzufragen. (Man muss sowieso die noch zu drückenden Modifier im State manuell setzen, bspw. Ctrl und Alt, damit die Abfrage korrekt ist.)
