### ISSUE TITLE
Fehler irgendwie kommunizieren

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#29]
Bis jetzt stürzen wir bei Fehlern im Release-Modus einfach ab. Besonders blöd ist das, wenn das beim Lesen einer der JSON-Dateien passiert, da der Nutzer nicht erfährt, wo er etwas falsch eingegeben hat. Wir sollten zumindest eine MessageBox anzeigen, die entweder die Exception ausgibt, oder auf den Debug-Modus verweist. Letzteren kann man vielleicht auch als zweite Binary mit schiffen?

**Comment by qwertfisch** [comment]
Eine Messagebox ist ja kein Problem. Fehlerkritische Bereiche (bei der Initialisierung) packt man in einen Try-Block und antwortet dann elegant mit einer Fehlermeldung. Fehler im laufenden Betrieb würde ich dann eher in eine Datei loggen, bevor man – wie AutoHotkey – dem Nutzer eine MsgBox im falschen Moment um die Ohren haut.
Debugversionen sollten eher für die Entwickler sein. Damit wird getestet und Fehler gefunden.

**Comment by Rojetto** [comment]
Es gibt jetzt Messageboxen für den Initialisierungsvorgang, sowie `reneo_debug.exe` mit allen Konsolenausgaben, die auch in einer Textdatei abgespeichert werden. Damit sollten die gröbsten Probleme abgedeckt sein.
