### ISSUE TITLE
Shortcuts Win+Zahl zum Fensterwechsel in Standalone/honest

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#30]
Gibt Zahl ein statt Fenster zu wechseln. Grund ist, dass mit aktuellem Mapping kein `VK_KEY_1` gesendet wird, sondern das Unicode-Zeichen der Zahl. Bei `fakeNative` tritt es deshalb nicht auf, weil dort der VK gesendet wird.

**Comment by qwertfisch** [comment]
Das dürfte sich gemeinsam mit #27 lösen lassen– oder wenn der honest-Mode wegfällt. Mir bestätigt es, dass gewisse Tasten ihren VK im Mapping behalten müssen, sonst hat man solche Nachteile. (Oder man baut die ganzen Sonderfälle explizit ein, aber eigentlich sollte Windows das selbst erledigen.)

Klappt übrigens auch mit nativem französischem Layout (ohne Reneo), obwohl dort die Ziffern auf der Shift-Ebene liegen.

**Comment by Rojetto** [comment]
Mit der gemeinsamen Lösung mit #27 meinst das, dass wenn man das gelöst hat man wieder VKs ins Mapping schreiben kann? Verstehe ich das richtig?

**Comment by qwertfisch** [comment]
Äh genau. Das habe ich nicht deutlich genug aufgeschrieben, war wohl doch etwas spät gestern.

**Comment by qwertfisch** [comment]
> Bei `fakeNative` tritt es deshalb nicht auf, weil dort der VK gesendet wird.

Jein, das funktioniert nur zufälligerweise mit dem deutschen Layout. Im französischen Layout z.B. liegen die Zahlen auf Shift+Zifferntasten, sodass ReNeo – welches eigentlich eine „3“ senden möchte – eine Shift-Taste hinzufügt. Dadurch wird Win+Shift+3 gesendet. Dies ist aber der Shortcut für _neue Instanz öffnen_.

In meinem Fall, weil ich nur in einem Fenster das französische Layout offen hatte, wurde ein neues Fenster mit deutschem Layout geöffnet. Das Loslassen der Taste 3 hatte zur Folge, dass das eingeschobene Shift nicht mehr losgelassen wurde. Es war ja bei deutschem Layout nicht nötig. Somit „klemmte“ die Shifttaste … (Das zeigt wiederum, warum AutoHotkey eingeschobene Modifier so schnell es geht wieder loslässt und dadurch Tastenrauschen erzeugt.)

Ich fürchte, hier führt kaum ein Weg dran vorbei, wieder die Virtual Keys für die Zifferntasten einzutragen. Oder man führt lauter Ausnahmen für Win-Shortcuts ein.

**Comment by Rojetto** [comment]
Franzosen ohne Numpad tun mir Leid... Klar kann man einfach wieder die VKs eintragen, zusammen mit dem Fix für #27 geht es dann für QWERTZ. Dann kommen bei Standalone+Azerty aber keine Ziffern mehr auf der ersten Ebene.

**Comment by qwertfisch** [comment]
Ist es einfacher, eine Azerty-Option für die Zifferntasten einzubauen, als das Shortcut-Handling für Zifferntasten zu übernehmen? Meine Überlegung ist eher, dass Azerty-gewohnte Tipper vermutlich auch nicht die Zifferntasten auf der ersten Ebene benötigen und sich ihr Bone/Neo/usw. dann einfach umkonfigurieren (E1 und E2 tauschen auf den Zifferntasten). Andersherum können wir auch festlegen, nicht jedes europäische Layout (ohne enormen Aufwand) vollständig zu unterstützen.

Meine favorisierte Lösung ist daher VKs für die Zifferntasten.

**Comment by Rojetto** [comment]
Nachdem ich jetzt zwischen allen möglichen Varianten selber den Überblich verloren habe, hier nochmal Tests für alle Kombinationen.

Durchgeführte Tests:
1. Nur Zahl
2. Shift + Zahl
3. Capslock + Zahl
4. Capslock + Shift + Zahl
5. Shortcut Win+Zahl

- Variante `char` stehen lassen
  - QWERTZ
    - `honest`: 1 ✔️  | 2 ✔️ | 3 ✔️ | 4 ✔️ | 5 ❌ (kein Effekt)
    - `fakeNative`: 1 ✔️  | 2 ✔️ | 3 ✔️ | 4 ✔️ | 5 ✔️
  - Azerty
    - `honest`: 1 ✔️  | 2 ✔️ | 3 ✔️ | 4 ✔️ | 5 ❌ (kein Effekt)
    - `fakeNative`: 1 ✔️  | 2 ✔️ | 3 ✔️ | 4 ✔️ | 5 ❌ (öffnet neues Fenster)
- Variante mit `vk`
  - QWERTZ
    - `honest`: 1 ✔️  | 2 ✔️ | 3 ❌ (erzeugt QWERTZ Ebene 2 Zeichen) | 4 ✔️ | 5 ✔️
    - `fakeNative`: 1 ✔️  | 2 ✔️ | 3 ❌ (erzeugt QWERTZ Ebene 2 Zeichen) | 4 ✔️ | 5 ✔️
  - Azerty
    - `honest`: 1 ❌ (erzeugt französischen Blödsinn)  | 2 ✔️ | 3 ✔️ | 4 ✔️ | 5 ✔️
    - `fakeNative`: 1 ❌ (erzeugt französischen Blödsinn)  | 2 ✔️ | 3 ✔️ | 4 ✔️ | 5 ✔️

Die einzige vollständig richtige Variante davon ist `char`, mit QWERTZ und `fakeNative`. Deshalb würde ich sagen der Honest-Modus hat sowieso fraglichen Nutzen, bis man den findet kann man auch einfach `fakeNative` nehmen. QWERTZ kann man sich auch installieren, wer unbedingt nativ Azerty will muss halt iwie sein Mapping ändern. Wenn man dann `char` stehen lässt ist die Welt in Ordnung.

Fazit: nichts machen
