### ISSUE TITLE
`config.json` zwischen Upgrades nicht zerschießen

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#46]
Momentan kopiert man beim Upgrade einfach alle Dateien aus der ZIP über sein Installationsverzeichnis. Wenn man nicht manuell merged überschreibt man so seine Einstellungen in `config.json`.

Im Release sollte deshalb keine `config.json` mehr enthalten sein, sondern nur eine `config.default.json`. Führt man dann ReNeo aus, lädt es die existierende `config.json` (falls bereits vorhanden) und ergänzt fehlende Einträge mit denen aus `config.default.json`. Dann wird `config.json` geschrieben, sodass sie ihre alten Einstellungen behält, aber auch die Standardwerte für alle Einstellungen der neuen Version vorhanden sind.

Der Upgrade-Prozess muss in der README dokumentiert werden.

**Comment by qwertfisch** [comment]
Programmiertechnisch scheint es andersherum sinnvoller: zuerst die `config.default.json` einlesen, dann die Variablen mit den nutzerspezifischen Einträgen aus `config.json` überschreiben. Anschließend abspeichern.

Wenn es deutlich mehr Einträge werden, sollte man sich über ein wirkliches Ini-Format mit Abschnitten, Kommentaren und gleichbleibender Sortierung Gedanken machen. Aktuell sortiert `toJSON()` alles alphabetisch.

**Comment by Rojetto** [comment]
Öh, ja. In der Implementierung ist andersherum natürlich einfacher.

> Wenn es deutlich mehr Einträge werden
Dem Problem stellen wir uns, wenn es tatsächlich kommt. Aktuell finde ich die JSON-Lösung noch vertretbar.
