### ISSUE TITLE
Programmspezifische Layouts

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#47]
In manchen Programmen muss man ReNeo für gute Kompatibilität immer deaktivieren, zum Beispiel [VcXsrv](https://github.com/Rojetto/ReNeo#wsl-mit-vcxsrv-als-x-server) oder in Spielen. Das soll konfigurierbar automatisch gehen.

Mögliche Faktoren zum Erkennen eines Programms sind der Pfad der Anwendung oder der Fenstertitel (mit Wildcards). Ein Hook für den Fensterwechsel existiert bereits.

Wenn man nicht nur deaktiviert, sondern ein beliebiges Layout einstellen kann, lässt sich so evtl. auch #11 lösen.

**Comment by tinloaf** [comment]
Hooray! Werde ich morgen gleich testen. :+1:
