### ISSUE TITLE
Layer friert ein beim benutzen der Pfeiltasten oder page up page down 

### ISSUE THREAD

**Issue by cryptointerest** [Rojetto/ReNeo#49]
Moin, 

Wenn ich die rechte Alt Gr Taste drücke um wie gewohnt den Navigationsblock zu nutzen hängt sich Reneo immer mal wieder auf  und die vierte Ebene bleibt eingestellt. Man kann sie danach nicht wieder abgestellen. 
Die exe muss dann abgeschossen werden (z.T. mit Taskmanager) und danach muss man z. T. noch mal Alt Gr + NUM LOCK drücken (oder andere Kombinationen, ich weiß es nicht genau) bis sich das verhakte wieder löst. 

Gibt es eine Debugoption, welche output generiert, sodass ich euch ein log anhängen kann?

Viele Grüße und danke für eure Arbeit, 
David

**Comment by Rojetto** [comment]
Um das Problem ein bisschen einzugrenzen, ein paar allgemeine Fragen:
1. Benutzt du ReNeo Standalone oder als Erweiterung mit z. B. kbdneo?
2. Warum musst du mit dem Taskmanager beenden? Reagiert das Tray-Menü nicht mehr?
3. Hast du mehrere Sprachen in Windows installiert? Kann es sein, dass du zwischendurch aus Versehen das native Layout wechselst?

Als Log bräuchten wir idealerweise die Sequenz von Tastendrücken, die zur Verhakung geführt hat; also einen Keylogger 🙃 Wenn du das wirklich willst (kann voll verstehen, wenn nicht), kannst du [hier](https://qwertfisch.eu/reneo/keylogger.exe) einen herunterladen (ist auch von uns). *Wichtig*: Der Logger muss *nach* ReNeo gestartet werden. **Alle** Tastendrücke werden dann aufgezeichnet und in eine Textdatei neben der EXE geschrieben. Die kannst du manuell von sensiblen Daten säubern und (wenn du möchtest) hier anhängen. Schreibe bitte mit dazu, ab wann du die Verhakung bemerkt hast.

**Comment by cryptointerest** [comment]
N'Abend, 

1) Ich nutze ReNeo standalone ohne kdbneo, da dies die einzige Möglichkeit ist neo auf meinem Firmenrechner zu nutzen. (Musste schon Wochen mit der IT kämpfen, damit das überhaupt ging). Die IT möchte keinen IT support für kdbneo gewähren, wenn etwas nach einen Win10 Update kaputt geht. 

2) Es ist unterschiedlich. Typischerweise kille ich über das Applet, aber danach ist das Keypoard immer noch gesperrt. Ich versuche dann immer eine Kombination von Alt Gr + Numlock, oder shift + Numlock oder irgend so etwas. Irgendwann entklemmt sich das keyboard und die querty Tastatur des Standardlayouts. Ich habe noch nicht genau herausgefunden, was ich drücken muss und warum es noch klemmt, wenn die Exe tot ist. Mir ist es aber auch schon passiert, dass eine ReNeo Exe noch aktiv war (ohne als Applet sichtbar zu sein), aber ich hatte eine weitere Instanz gestartet. Dann half nur noch der Task Manager. 

3) Sehr unwahrscheinlich. Es fing auch schon an zu hängen nachdem ich Alt Gr und „Enter“ also v gedrückt habe. Das ist doch recht weit weg von der <>| Taste, die LMod4 ist. Ich werde noch einmal verstärkt darauf achten und morgen mal versuchen explizit Ebene 4 zu sperren. 

4) Es ist noch das US Layout installert. Ist aber unwahrscheinlich, da die Ebene vier einfach klemmt und nicht das US Layout aktiviert wird. Ich werde es morgen aber mal deaktivieren.

Das mit dem Keylocker muss ich noch überlegen. Ist halt ein Firmenlaptop.

**Comment by Rojetto** [comment]
Zu 2.: Was genau meinst du mit „gesperrt“? Ich habe es jetzt so verstanden, dass dann ReNeo wirklich beendet ist (wenn es nicht mehr im Taskmanager auftaucht läuft es nicht). Was passiert dann genau, wenn du in diesem „gesperrten“ Zustand Tasten drückst? Welche Zeichen/Steuerbefehle entstehen da?

Wenn du es selbst zuverlässig reproduziert bekommst wäre das natürlich ideal. Das macht es auch für uns viel einfacher, als im Log herumzuinterpretieren.

Darf ich fragen, was das für ein Laptop ist? Ich hatte bei mir auch schon Fälle, wo seltsames Tastenverhalten auf die Hardware zurückzuführen war, die bestimmte (in QWERTZ unübliche) Tastenkombinationen nicht mochte.

**Comment by cryptointerest** [comment]
Es ist schon vorgekommen, dass ich über das Applet Reneo beendet habe und danach das Keyboard immer noch nicht normal war. Ich verstehe auch nicht warum. Meine Vermutung ist, dass man im Quertylayout die AltGr Taste feststellen kann und das irgwendwie ausgelöst wird (kann so etwas überhaupt sein? K.P. )
Ich versuche es morgen noch einmal auszulösen. Bisher passierte es ziemlich unnachvollziehbar. 

Das Gerät ist ein Dell Latitude. Die genaue Nummer weiß ich nicht auswendig.

**Comment by Rojetto** [comment]
Tut mir Leid wenn ich mich wiederhole :) Was genau heißt „immer noch nicht normal“? Was passiert, wenn du in dem Zustand Tasten drückst?

AltGr feststellen sollte nach meinem Verständnis nicht gehen, und selbst wenn sich spätestens lösen, sobald man AltGr nochmal drückt. Aber ich will hier nichts voreilig ausschließen.

**Comment by cryptointerest** [comment]
es kommen keine Buchstaben. Stattdessen springt der Curser undefiniert hin und her.

**Comment by Rojetto** [comment]
Spannend. Wenn ReNeo nicht mehr läuft, sollte das nicht möglich sein. Ein „AltGr-Lock“ unter QWERTZ würde höchstens dazu führen, dass die jeweiligen AltGr-Sonderzeichen kommen.

Wenn es das nächste Mal auftritt, kannst du vielleicht systematisch probieren, was die einzelnen Tasten *genau* machen? Ich könnte mir 3 Fälle vorstellen:
1. Verhalten wie bei Mod4-Lock, das heißt es kommen die Steuerzeichen der Ebene 4. Auf der linken Seite also Cursor-Tasten, auf der rechten Seite das Numpad.
2. Verhalten wie Mod4-Lock, aber mit permutierten Tasten.
3. Etwas anderes (was genau?)

Wäre schön wenn du herausfindest, welcher der Fälle es ist. Schau bitte auch, ob sich das Verhalten vor und nach dem Beenden von ReNeo verändert.

Die genaue Modellnummer des Laptops würde mich auch interessieren. Ich habe gesehen, dass manche Dell-Geräte eine eigene Numpad-Ebene im Hauptfeld haben. Vielleicht ist auch die der Übeltäter. Dafür würde ich aber gerne mal ins passende Handbuch schauen.

**Comment by cryptointerest** [comment]
Die genaue Modellnummer ist Dell Latitude 5420

**Comment by cryptointerest** [comment]
Also, gerade ist es wieder passiert, ich hatte im Editor versucht das verhalten auszulösen. Beim verwenden der sechsten Ebene AltGr + #-Taste trat die Verklemmung auf. 
Das Verhalten ist aber nicht wirklich klar. Es ist nicht jenes der vierten Ebene, sondern viele Tastenanschläge führen zum Öffnen irgendwelcher Dialoge, so z. B. Suchen & Ersetzen, Oder es wird eine Zeile Blau markiert. 
Völlig seltsam. 
Mir ist dann aufgefallen, dass wenn ich die Modifiere gedrückt halte die Nummerzeile zu Mindest Teilweise funktioniert. 
Ich habe explizit versucht den Lock mit den beiden Mod4 Tasten zu lösen, ohne Erfolg.

**Comment by Rojetto** [comment]
Bingo! Mit der Beschreibung konnte ich es nachstellen.
- RMod4 (AltGr) + RMod3 (QWERTZ-#) + QWERTZ-q → Ξ. Danach ist es so verklemmt, wie du beschrieben hast.
- Es löst sich mit Shift+7 (€).

Damit ist die Lösung nicht weit :)

**Comment by Rojetto** [comment]
Als ich den letzten Kommentar geschrieben habe, ließ es sich tatsächlich so zuverlässig reproduzieren. Jetzt bekomme ich es nur noch mit RMod4+RMod3+wildem Tastenhämmern hin.

Nichtsdestotrotz scheint es nach nach dem letzten Commit bei mir gelöst. Mit minutenlangem Tastenhämmern nach dem problematischen Schema verhakt es sich immer noch nicht. Die Änderung landet dann im nächsten Release.

**Comment by cryptointerest** [comment]
Cool! Maschine! 
Ich bin gespannt. Es tritt ja auch oft auf, wenn ich den Navigationsblock verwende. Bin gespannt, ob die Änderungen alle Fälle lösen. 
Aber falls es nach dem Fix noch einmal auftritt gibt es ja schon eine Idee, woran es liegen könnte. =). 

Soll ich das Issue schließen?

**Comment by Rojetto** [comment]
Änderung ist in [v1.4.1](https://github.com/Rojetto/ReNeo/releases/tag/v1.4.1). Wenn es trotzdem noch auftritt, bitte melden.
