### ISSUE TITLE
Laden von .remove-Modulen bei Compose

### ISSUE THREAD

**Issue by qwertfisch** [Rojetto/ReNeo#5]
Bei Neo lässt sich aus den einzelnen Compose-Modulen ein gemeinsames Modul generieren (die `.XCompose`). Um Konflikte zu vermeiden (bzw. unerwartete Ergebnisse), können Module auch bereits vorhandene Einträge löschen. Die zu löschenden Zeilen sind in `.remove`-Dateien enthalten. Näheres zur Umsetzung siehe [Neo-Repository#574](https://git.neo-layout.org/neo/neo-layout/pulls/574).

Dies umzusetzen wäre praktisch, da bei ReNeo die gleichen Compose-Module verwendet werden (können), die jedoch interne Überschneidungen besitzen.

**Comment by Rojetto** [comment]
Für zwei Module `a` und `b` sähe die Reihenfolge der angewandten Dateien dann aus wie

```
a.remove
a.module
b.remove
b.module
```

Verstehe ich das richtig? Aus dem makefile kann ich das nicht so richtig rauslesen.

Damit das die erwarteten Ergebnisse liefert müssten die Module auch nicht in alphabetischer Reihenfolge angewandt werden, sondern in der gleichen wie die mit der sie im Makefile zusammengebaut werden.

**Comment by qwertfisch** [comment]
Die Reihenfolge ist tatsächlich egal, wenn die .remove-Dateien nur nach allen Modulen prozessiert werden.

Ein Eintrag in einer .remove-Datei bewirkt, dass eine exakt gleiche Zeile, die vorher aus einem anderen Modul inkludiert wurde, wieder rausgenommen wird. Das Makefile baut die XCompose sukzessive zusammen, und am Ende bleibt der gewünschte Eintrag (für eine gegebene Kombination) dort übrig. Nach der Art sollte auch ReNeo arbeiten – eventuell ist hier eine Vorverarbeitung notwendig.

Das ist zumindest, was mir vom Autor erklärt wurde. Die grep&sed-Magie im Makefile durchsteige ich auch nicht 100%ig.

Hätte man diese Removes nicht, gäbe es mehrere Einträge für die gleiche Kombination. Dann wäre nämlich tatsächlich die Ladereihenfolge entscheidend (letzter Eintrag gilt).

**Comment by Rojetto** [comment]
Mit 10a4d69216e48bc59742e6904afe47f4d24b1978 umgesetzt.
