### ISSUE TITLE
Numlock wird Aktiviert

### ISSUE THREAD

**Issue by Niko4u5** [Rojetto/ReNeo#50]
Wie kann ich verhindern das ReNeo Numloc aktiviert?

Wenn ich das Programm ausführe wird nach dem ersten Tastenanschlag numlock aktiviert, da bei meinem Laptop das numpad auf den Buchstaben liegt, werden an diesen stellen dan Zahlen stat Buchstaben ausgegeben.

**Comment by Rojetto** [comment]
Danke für die Meldung. Dass Numlock bei solchen Laptops diese Funktion hat war mir nicht bewusst.

Könntest du bitte [v1.4.2](https://github.com/Rojetto/ReNeo/releases/tag/v1.4.2) testen und Rückmeldung geben? Wenn du die neue Option `autoNumlock` auf `false` setzt, sollte das nicht mehr passieren.

**Comment by Niko4u5** [comment]
Vielen Dank für die schnelle Antwort.
Die Tasten auf Ebene 1 Funktionieren jetzt einwandfrei.
In manchen Programmen funktionieren die Zahlen auf Ebene 4 nicht, da Numloc nicht Aktiviert ist, werden die Zahlen als Pfeiltasten interpretiert.
Ich habe jetzt in der layouts.json die Numpad zahlen durch Normale Zahlen ersetzt und noch keine weiteren Probleme bemerkt.

**Comment by Rojetto** [comment]
Jepp, das Problem, das du mit ausgeschaltetem Numlock gesehen hast, ist vermutlich #32. Eine 100%-Lösung werden normale Zahlen auch nicht sein, da manche Programme Shortcuts explizit nur auf das Numpad mappen. Aber bis das dir tatsächlich auftritt sollte deine Lösung ein benutzbarer Workaround sein.
