### ISSUE TITLE
Feature request: Tastenkombinationen senden

### ISSUE THREAD

**Issue by MaxGyver83** [Rojetto/ReNeo#54]
All die nützlichen Tasten in Ebene 4 haben den Vorteil, dass man sie gut erreichen kann, aber auch den Nachteil, dass man immer eine zusätzliche Taste drücken muss (eine der Mod4-Tasten). Das ist zwar kein Problem, wenn man nur `BildAuf` oder `Escape` auf Ebene 4 benutzen will. Wenn man aber `Strg-Shift-PfeilLinks` eingeben will (um das vorherige Wort zu markieren), muss man dafür schon 4 Tasten gleichzeitig drücken.

Deshalb wäre es cool, wenn eine Taste (in einer bestimmten Ebene) eine Kombination (wie `Strg-Shift-PfeilLinks`) senden könnte. Sowas ist in KMonad (und ich glaube auch in QMK) möglich. In meiner [KMonad-Konfiguration](https://github.com/MaxGyver83/dotfiles/blob/79ae5ce1eee0517fd695b6393a769e1535da0132/kmonad/.config/kmonad/vou-linux-de-rctrl.kbd#L67) nutze ich eine Ebene, über die ich `Strg-BildAuf/Ab` (=vorheriger/nächster Tab in vielen Programmen), `Strg-Tab` (=[zeitlich] letzter Tab) oder `Strg-Backspace` (letztes Wort löschen) senden kann, ohne eine dritte Taste drücken zu müssen.

Diese Funktion wäre insbesondere in Kombination mit #51 sehr nützlich.

**Comment by Rojetto** [comment]
Umgesetzt in [v1.5.0](https://github.com/Rojetto/ReNeo/releases/tag/v1.5.0). Zusätzlich zum `vk` können jetzt im Mapping auch noch Modifier à la `"mods": {"LShift": true, "LCtrl": true}` angegeben werden. Strg, Shift und Alt können außerdem beliebig umgeordnet werden, hatte gesehen die Funktion gab es in neo2-llkh auch.
