### ISSUE TITLE
Scheduled Task überschreibt `config.json` mit Defaults

### ISSUE THREAD

**Issue by kaimi** [Rojetto/ReNeo#58]
Wenn man den Anweisungen unter https://neo-layout.org/Einrichtung/kbdneo/#reneo-mit-administratorrechten folgt, wird `config.json` jedes mal mit den Defaults überschrieben.

Das Problem löst sich in Luft auf, wenn man der `Action` manuell das richtige working directory mitgibt.

Ich vermute mal, der Check für „existiert `config.json`?“ passiert _vor_ dem korrekten Setzen des working directory.

**Comment by Rojetto** [comment]
Danke für die Meldung! Eigentlich™ wollen wir unabhängig vom Arbeitsverzeichnis immer dort nach Dateien schauen, wo auch die EXE liegt. Wie du richtig vermutest hast, hat sich dort ein Fehler eingeschlichen.
