### ISSUE TITLE
`toggleActivation` hotkey schluckt Tasten

### ISSUE THREAD

**Issue by kaimi** [Rojetto/ReNeo#61]
Ich habe da jetzt noch nicht wirklich hinterherrecherchiert, was genau das Problem (und der Umfang) ist; aber für meine Konfiguration von `Mod3+F5` (well, `OEM_102+F5`) schluckt ReNeo `F5`. Auch ohne `Mod3` zu drücken kommt kein `F5` mehr an.

**Comment by Rojetto** [comment]
> Erlaubte Modifier sind Shift, Ctrl, Alt, Win.

Der Hotkey zum Aktivieren muss funktionieren, wenn der Tastaturhook nicht aktiv ist (weil ReNeo eben deaktiviert ist). Deshalb registrieren wir ihn global in Windows, das kein M3 und M4 kennt.

Ich habe deine Konfiguration getestet:
```json
"hotkeys": {
    "toggleActivation": "Mod3+F5",
    "toggleOSK": null
}
```
Wenn ich dann ReNeo starte, bekomme ich ordnungsgemäß diese Fehlermeldung:
![image](https://user-images.githubusercontent.com/777285/129490853-2bf54de2-04d0-4caf-987b-e4117d221c9c.png)

Ist das bei dir nicht der Fall?

**Comment by kaimi** [comment]
`"toggleActivation": "OEM_102+F5",`

**Comment by kaimi** [comment]
> Erlaubte Modifier sind Shift, Ctrl, Alt, Win.

Tja, den Teil muss ich wohl übersehen haben :)
