### ISSUE TITLE
Weitere Virtual-Key Codes möglich für hotkeys?

### ISSUE THREAD

**Issue by ypid-geberit** [Rojetto/ReNeo#62]
Ich würde gerne [meine gewohnten Tastenkürzel](https://github.com/ypid/dotfiles/blob/master/docs/shortcuts.md) auch mit ReNeo benutzen:

```
    "hotkeys": {
        "toggleActivation": "Shift+Alt+A",
        "toggleOSK": "Ctrl+Alt+Q"
    },
```

Das scheitert allerdings mit dieser Fehlermeldung: "Beim Starten von ReNeo ist ein Fehler aufgetreten: VKEY does not have a member named 'VK_A'"

Der Text unter [Allgemeine Konfiguration](https://github.com/Rojetto/ReNeo#allgemeine-konfiguration) beschreibt es sehr genau: "Die Haupttaste ist ein beliebiger **VK** aus [dieser Liste](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)."

Folgendes funktioniert dementsprechend:

```
        "toggleOSK": "Ctrl+Alt+SPACE"
```

Ist es möglich, weitere Virtual-Key Codes in Kombination mit den erlaubten Modifiern zu unterstützten?

Ref: #61
Cc:  @kaimi

**Comment by Rojetto** [comment]
An der Stelle ist die Doku nicht ganz so präzise, wie es den Anschein
macht. Tatsächlich ausschlaggebend ist diese Enum im Quelltext:
https://github.com/Rojetto/ReNeo/blob/5bd304a7c42c768ed45813095ab5fbc69103773c/source/mapping.d#L17

Demzufolge sollte es bei dir funktionieren, wenn du "Shift+Alt+KEY_A" und
"Ctrl+Alt+KEY_Q" einstellst.

Robin Schneider ***@***.***> schrieb am Mo., 16. Aug. 2021,
12:00:

**Comment by ypid-geberit** [comment]
Funktioniert, vielen Dank für ReNeo und die Hilfe!
