### ISSUE TITLE
manche mathematische Zeichen werden nicht angezeigt

### ISSUE THREAD

**Issue by der-reisende** [Rojetto/ReNeo#65]
Umgebung:
Reneo 1.5
Windows 11 (21H2)
ReNeo_Neo
standaloneMode: false (mit Treiber)

Reproduktion des Fehlers:
Drücken von M4+M3+o bzw. M4+M3+s
Erwartet: Anzeige Element-von-Zeichen und Summenzeichen
Ergebnis: es wird nichts angezeigt.
Ausprobiert in Word, Outlook, Notepad, Notepad++, Opera Browser
Dito für Omega (E6:w), Kreuzprodukt (E6:k), Verkettungszeichen (E6:ß) und Nabla (E6:y)

Was kann ich tun, um mehr Informationen für die Fehlerbehebung beizusteuern?

**Comment by Rojetto** [comment]
Danke für die Meldung! Ein System mit Windows 11 habe ich gerade nicht zur Hand, das würde ich später mal ausprobieren. In der Zwischenzeit habe ich es unter Windows 10 getestet und da funktioniert es mindestens in VS Code und Notepad.

Folgende Fragen:
- Funktioniert es mit *kbdneo*, wenn *ReNeo* nicht läuft (beendet ist)?
- Betrifft es nur die angesprochenen Zeichen oder alle Zeichen der Ebenen 5 und 6?
- Welche Mod3- und Mod4-Tasten drückst du (links/rechts)? Hast du mal andere Varianten (zum Beispiel Mod4-Links, Mod3-Rechts) probiert? Möglicherweise könnte es nämlich auch ein Problem der physischen Verschaltung deiner Tastatur sein, die solche Kombinationen (die sonst ja unüblich sind) nicht mag.
- Was passiert, wenn du in `layouts.json` auf den entsprechenden Tasten kein mathematisches Sonderzeichen sondern einen normalen Buchstaben mappst? Dazu kannst du zum Beispiel Zeile 82 ersetzen mit `"22": [{"keysym": "o", "vk": "VK_KEY_O", "label": "o"},                 {"keysym": "O", "vk": "VK_KEY_O", "label": "O"},                {"keysym": "asterisk", "char": "*"},                        {"keysym": "End", "vk": "VK_END", "label": "\u2198"},           {"keysym": "Greek_omicron", "char": "ο"},                           {"keysym": "a", "vk": "VK_KEY_A", "label": "a"}],`

**Comment by der-reisende** [comment]
- Funktioniert es mit kbdneo, wenn ReNeo nicht läuft (beendet ist)?
mea culpa, ich hatte gedacht, dass die Ebene 6 von ReNeo bedient wird, aber es ist anscheinend ein Problem, das mit dem Treiber zusammenhängt. Nein, es funktioniert auch nicht, wenn ReNeo beeendet ist.

aber:
- Welche Mod3- und Mod4-Tasten drückst du? 
Das war wohl die Lösung. Ich hatte links/links ausprobiert, aber mit rechts/links und rechts/rechts funktionieren alle Tasten.


- Betrifft es nur die angesprochenen Zeichen oder alle Zeichen der Ebenen 5 und 6?
Nur der Vollständigkeit halber, weil ich dies zuerst bearbeitet hatte und danach erst mod3/mod4 ausprobiert habe:
Ebene 6: die meisten funktionieren, habe aber jetzt noch ein paar gefunden, die nicht gehen: der Strich neben der 0 erzeugt keinen Strich, bei der Leertaste bin ich mir gerade nicht sicher, was da erzeugt werden soll, Im NumPad geht die Ecke auf der 1 nicht, Anführungszeichen auf dem Komma, der Strich auf dem "geteilt durch", das Plus erzeugt auch kein Zeichen., das sollte es ungefähr sein (ich orientiere mich am On-Screen-Display-Keyboard)
Ebene 5: es gehen nicht: die 2 (tiefgestellt), der "Haken?" auf dem i, das kleine "Element von" auf dem ö. Der Rest funktioniert.

- layouts.json 
habe ich jetzt nicht mehr ausprobiert...


Danke!

**Comment by Rojetto** [comment]
> ich hatte gedacht, dass die Ebene 6 von ReNeo bedient wird

Da hast du auch richtig gedacht. *kbdneo* hat zwar selber die Ebenen 5 und 6, aber aus Gründen der Kompatibilität übernimmt *ReNeo* die, wenn es läuft. War hier aber wohl nicht das Problem.

> Ich hatte links/links ausprobiert, aber mit rechts/links und rechts/rechts funktionieren alle Tasten.

Gut, dann liegt es daran. Da das Problem auf physischer Ebene liegt, kommen nicht einmal alle Tastenanschläge im Betriebssystem an, hier können wir also leider nichts machen. Zum Glück wirst du die Ebenen 5 und 6 nicht so häufig brauchen; und sonst hast du ja den Workaround.

**Comment by qwertfisch** [comment]
> bei der Leertaste bin ich mir gerade nicht sicher, was da erzeugt werden soll

Ein schmales geschütztes Leerzeichen (U+202F), siehe [Wiki hier](https://neo-layout.org/Benutzerhandbuch/Tastaturbelegung/#ebene-6) und mit Erklärung [hier](https://neo-layout.org/Tips/Leerzeichen/). Ich benutze es aber auch nur, wenn ich meinen peniblen Tag habe.

Bei meiner billigen Tastatur klappen auch ein paar Tasten nicht, wenn ich Mod5 oder Mod6 nur links bzw. nur rechts versuche. Schlimm sind E5 rechts/rechts (sechs Zeichen) sowie E6 links/links (13 Zeichen). Bei den jeweils anderen Ebenen geht nur je ein Zeichen nicht … Ist verschmerzbar, die sind auch so, dass die jeweils andere Seite klappt. Ich muss also nicht „gemischte“ Modifier benutzen.
