### ISSUE TITLE
Reneo schließt sich nach Eingabe von Zeichen nach Öffnen von cmd.exe, pwsh

### ISSUE THREAD

**Issue by marincandenza** [Rojetto/ReNeo#66]
**SW-Umgebung**
1. W10 Enterprise mit angewandter Gruppenrichtlinie
2. Systemsprache English, Benutzersprache Deutsch
Anmerkung: Ich habe es bis jetzt nicht hinbekommen, das US Layout zu deaktivieren. Englisch wird als Systemsprache verwendet und kann daher nicht gelöscht werden; Nur das neo2 Layout ist in Windows Spracheinstellungen eingestellt

**Betrifft Versionen**
1.5.0, 1.4.6 und evtl. weitere 

**Auslöser**
Verschiedene Einstellungen / Versuche Englisch als Systemsprache zu deaktivieren haben zum ständigen Absturz von reneo geführt.
Zuletzt Anmeldesprache von Englisch auf Deutsch gesetzt
**Problem** ist: Sobald in pwsh.exe oder Lock-Screen gewechselt wird, ist US Layout eingestellt, daher habe ich versucht, das US Layout zu entfernen, ohne Erfolg. Derzeit liegt eine OS Einstellung vor, die reneo prompt zum Absturz bringt, wenn z.B. in cmd.exe, Jetbrains Tools, pwsh.exe, etc. getippt werden.

**Comment by marincandenza** [comment]
Nachtrag: Nachdem ich das Layout neo2 entfernt habe und in den folgenden Einstellungen _Aktueller Benutzer_ und _Willkommensseite_ (links) Deutsch wieder eingestellt hatte, hat sich neo nicht mehr geschlossen. 
Das entfernen von neo2 als Layout hat wahrscheinlich geholfen, dass nicht immer auf US Layout umgestellt wird. 
![image](https://user-images.githubusercontent.com/45242624/132365206-7850847f-35b8-482d-aff3-f77aa24a1c04.png)

**Comment by Rojetto** [comment]
Danke für die Meldung! W10 Enterprise habe ich leider nicht selbst zum Testen da und in der Professional Edition fehlen die Einstellungsfenster in deinen Screenshots. Eine potentielle Ursache für den Crash habe ich zwar gefunden und behoben, praktisch ging dort bei mir auch vorher nichts schief.

Ich habe deinen letzten Stand folgendermaßen verstanden: Die Systemsprache ist Englisch, aber als Benutzersprache hast du wo es nur geht Deutsch (mit QWERTZ) eingestellt. Neo2 als natives Layout (*kbdneo*) kommt nicht mehr vor. Korrekt?

Jetzt kann ReNeo ja nur noch im Standalone-Modus laufen, das heißt vermutlich kannst du fast überall Neo tippen, aber nicht auf dem Anmeldebildschirm, richtig?

**Comment by alterNERDtive** [comment]
> Anmerkung: Ich habe es bis jetzt nicht hinbekommen, das US Layout zu deaktivieren. Englisch wird als Systemsprache verwendet und kann daher nicht gelöscht werden; Nur das neo2 Layout ist in Windows Spracheinstellungen eingestellt

Das kann ich so (auf Win 10 Pro) nicht nachvollziehen. Meine Sprache is Englisch, Zahlen-/Daten-/whatever-Formate sind auf Deutsch, einziges layout is Neo 2 (kbdneo). :thinking:

**Comment by Rojetto** [comment]
@marincandenza hattest du mal versucht, die "preferred languages" umzusortieren? Bei mir steht das System auf Englisch, aber wenn in dieser Liste Deutsch (Neo2 oder QWERTZ, wie man will) ganz oben steht, wird das standardmäßig auch als Layout ausgewählt.

![image](https://user-images.githubusercontent.com/777285/132680149-e160138c-a23c-426e-8fc3-1250d7abe60d.png)

**Comment by alterNERDtive** [comment]
![image](https://user-images.githubusercontent.com/53827887/132680861-f69698f3-a57d-4fec-9110-96e36cd7767b.png)
![image](https://user-images.githubusercontent.com/53827887/132680934-0263bcf7-91bd-4e28-a187-e3c336b70f97.png)
![image](https://user-images.githubusercontent.com/53827887/132681234-1bba9a65-6278-46a6-ba57-9e8d43a72d1b.png)

(Deutsche Formate ließen sich auch nur über die „alten“ “Administrative language settings“ einstellen, die „neue“ Oberfläche läßt nur Varianten der eingestellten Sprache zu …)

**Comment by marincandenza** [comment]
Die ersten beiden Fragen kann ich mit ja beantworten. Ich kann nun wieder
nahtlos in verschiedenen Systemen und Programmen tippen und bin sehr
erfreut!

Bei den preferred languages war meiner Erinnerung nach nur Deutsch
eingestellt.

Vielen Dank für die Hilfe die Implementierung von reneo!

alterNERDtive ***@***.***> schrieb am Do., 9. Sept. 2021,
13:55:

**Comment by Rojetto** [comment]
Schön, dass es sich offenbar gelöst hat. Der Crash darf natürlich trotzdem nicht sein, egal was in Windows eingestellt ist. Falls das wieder auftritt (vielleicht wenn du nochmal wagst, *kbdneo* für den Anmeldebildschirm zu installieren), bitte hier gerne kommentieren. Bis dahin wüsste ich gerade nicht, wie ich das Problem nachstellen und damit beheben könnte.

**Comment by marincandenza** [comment]
Wenn ich Langeweile habe kann ich nochmal umstellen :)
Habt ihr eine debug Version bzw. Kann ich das Logging scharf schalten?

Robert Heedt ***@***.***> schrieb am Do., 9. Sept. 2021,
18:54:

**Comment by Rojetto** [comment]
@marincandenza Ab v1.5.1 ist in der ZIP auch `reneo_debug.exe` enthalten. In der Konsole sieht man dann ein paar Debug-Ausgaben, außerdem wird alles in `reneo_log.txt` abgespeichert. Achtung: bitte aufpassen, dass du nicht aus Versehen deine Passwörter damit leakst.
