### ISSUE TITLE
Veraltete/Fehlerhafte Version auf neo-layout.org

### ISSUE THREAD

**Issue by liam-k** [Rojetto/ReNeo#67]
Hey! Erstmal vielen Dank für ReNeo. Es freut mich sehr, dass Neo wieder ein bisschen Liebe bekommt und bei meinem Umstieg sind direkt einige anstrengende Bugs verschwunden, mit denen ich beim neovars-Treiber immer zu kämpfen hatte. 

Allerdings scheint es so, als sei die Version, die auf https://neo-layout.org/Download/ bereitgestellt wird, fehlerhaft oder stark veraltet. (Ich habe nur die ReNeo_Neo-Version getestet.)

Aufgefallen ist es mir anhand der config.json, die bei der Variante, die man auf der Homepage findet, auch direkt so heißt (statt config.default.json). Der Inhalt sieht folgendermaßen aus: 

```
{
    "standaloneLayout": "Neo",
    "standaloneMode": true,
    "sendKeyMode": "fakeNative",
    "osk": {
        "numpad": true,
        "theme": "Grey"
    }
}
```
zum Vergleich der Inhalt der config.default.json der Github-Version (1.5):
```
{
    "standaloneLayout": "Neo",
    "standaloneMode": true,
    "filterNeoModifiers": true,
    "autoNumlock": true,
    "osk": {
        "numpad": true,
        "theme": "Grey"
    },
    "hotkeys": {
        "toggleActivation": "Shift+Pause",
        "toggleOSK": null
    }
}
```
Es scheint aber nicht nur die Configdatei, sondern die Binary der Homepage-Version veraltet zu sein, denn diese Version akzeptiert keine Änderungen der config.json. Ich habe z.B. versucht, dort eine `"autoNumlock": false` Zeile einzusetzen, aber die Einstellung wird bei Ausführung ignoriert.

**Comment by Rojetto** [comment]
Kann die Verwirrung verstehen. Die Version auf der Homepage wird basierend auf den Releases hier manuell aktualisiert, das kann sich manchmal verzögern.

@qwertfisch willst du vielleicht v1.5.1 zum Anlass nehmen, nochmal neue Versionen hochzuladen? Man sieht jetzt auch im Tray-Menü, welche Version man gerade ausführt. Das sollte zumindest etwas Klarheit schaffen.

**Comment by qwertfisch** [comment]
Ja, sorry, da fehlt noch irgendwie eine Automatik, oder zumindest ein Ping, dass ich das dann manuell hochlade.

@liam-k Du kannst problemlos die aktuellen Github-Releases verwenden. Die Downloads auf der Neo-Homepage haben keine speziellen Anpassungen, hängen momentan nur etwas hinterher.

**Comment by qwertfisch** [comment]
Die aktuellen Versionen stehen nun auch auf neo-layout.org zur Verfügung.

@Rojetto Wie wäre es, wenn du die Inhalte des Archivs in einen Ordner ReNeo bündelst und dann erst zipst? Manchmal achtet man nicht so drauf, und dann hat man beim Entpacken einen Haufen loser Dateien im Elternverzeichnis herumliegen.

**Comment by Rojetto** [comment]
@qwertfisch Perfekt, danke. Guter Punkt mit der ZIP-Datei, habe das Release-Skript für die nächsten Versionen angepasst.
