### ISSUE TITLE
Add support for the Three Layout aka `3l`

### ISSUE THREAD

**Issue by Rojetto** [Rojetto/ReNeo#73]
`3l` is a keyboard layout primarily for English language users inspired by a simplification of the Neo layout: https://github.com/jackrosenthal/threelayout

Seeing as their Windows implementation is AHK based, they probably face similar issues as NeoVars did. They might also profit from the more advanced features we have, e. g. we already handle https://github.com/jackrosenthal/threelayout/issues/22. ReNeo should be able to support this layout with a few simple changes:
- #72
- Add `3l` to `layout.json`
- On-screen-keyboard:
    - Add ANSI layout option
    - Add option to hide the number row
    - Somehow rename M3 and M4 to Sym and Cur
- Add pre-configured release version with the appropriate settings

**Comment by qwertfisch** [comment]
Small addition: after reloading configuration, the OSK should be updated. Inserting `updateOSK();` after line 328 in `app.d` might be a good location.
