### ISSUE TITLE
Undo/Redo ist nicht implementiert

### ISSUE THREAD

**Issue by qwertfisch** [Rojetto/ReNeo#8]
Auf Ebene 4 ist das Neo-Z mit Undo bzw. Redo (Shift+E4) definiert. Zwar funktioniert Redo auch unter Linux nicht konsistent, aber Undo ließe sich durch Simulation von Strg+Z einbauen.

**Comment by Rojetto** [comment]
Redo halte ich insofern auch für fraglich, als dass sich Programme selber nie einig sind, ob sie `Strg+Y` oder `Shift+Strg+Z` verwenden wollen.

Undo lässt sich natürlich machen, mir stellt sich nur die Frage, wie man so einen Sonderfall im Mapping abbildet. Vielleicht kann man einen unbenutzten Windows VK missbrauchen und dann an allerletzter Stelle für diesen Sonderfall die Tastenkombination senden.

**Comment by qwertfisch** [comment]
Bei Redo weiß ich selbst nie, welche Tasten ich drücken muss. Viele Editoren und Eingabefelder haben inzwischen beide Kombinationen auf Redo gestellt.

Undo wird nicht der einzige Sonderfall bleiben, siehe mein Issue zum Numpad. Kann man nicht im Hook den Scancode und den aktiven Modifier prüfen und dann Strg+Z senden? kbdneo-AHK arbeitet doch auch so.

**Comment by Rojetto** [comment]
Klar, funktionieren würde das. Damit wäre halt die Position dieser Belegung auf der Tastatur hardcodiert und nicht mehr im anpassbaren Mapping abgebildet. Das vermeidet man mit dem anderen Hack, weshalb der mir besser gefällt.

Dem Thema #7 kann ich mich leider erst annehmen wenn ich wieder vor einer Tastatur mit Numpad sitze. Dort habe ich aber auch die Hoffnung, dass man den komischen hardcodierten Effekt einfach irgendwie „deaktivieren“ kann und die gewünschte Belegung dann ganz normal aus dem Mapping kommt.
