### ISSUE TITLE
Tastatur rastet regelmäßig in einer mysteriösen Ebene ein

### ISSUE THREAD

**Issue by andypillip** [Rojetto/ReNeo#81]
Ich benutze zum ersten Mal ReNeo auf Windows 10, und es passiert mir regelmäßig, dass eine Funktionstaste einrastet.

Der Buchstabe f öffnet plötzlich das Menü, Esc wechselt zwischen Anwendungen.

Welche Ebene/Taste ist das, und wie kann ich zurück wechseln ohne mich abzumelden?
Gibt es eine Möglichkeit zu verhindern, dass ich versehentlich diese Ebene aktiviere?
Könnte es sein dass es mit dem Drücken einer Ebenen-Taste mit gleichzeitigem Berühren des Touchpads zu tun hat?

Ich erinnere mich, dass ich auf Gnome/Linux auch regelmäßig Ebene 4 eingerastet habe, und dass 4 Tasten gleichzeitig das aufheben konnten. Ich finde diese Info nicht mehr, aber es scheint auch auf Windows nicht zu helfen.

Danke!

**Comment by Rojetto** [comment]
Die mysteriöse Taste ist vermutlich Alt. Wenn du vorher selber Alt gedrückt hast, sollte sich die Verhakung mit der linken Alt-Taste lösen lassen. Wahrscheinlicher ist aber, dass das Alt-Event von einem Sonderzeichen kam, das mit einer AltGr-Tastenkombination realisiert wird (die die rechte Alt-Taste benutzt). Du kannst also probieren beispielsweise @ oder € zu tippen.

Verhindern kannst du das leider nicht, mit dem Touchpad hat es denke ich auch nichts zu tun.

Falls du keinen zuverlässig reproduzierbaren Fall findest, gehe ich davon aus, dass grundsätzlich kein Fehler im Code ist. Der Hook-Mechanismus in Windows (über den ReNeo Tastenevents modifiziert) ist leider etwas frickelig und fängt bei hoher Systemauslastung an, Events einfach wegzuschmeißen. Wenn dann ein Up-Event fehlt, bleibt die Taste hängen.

Ich merke selber auf meinem Laptop selten ähnliche Probleme, auf meinem stärkeren Desktop-PC hingegen ist es noch nie vorgekommen. Das Issue lasse ich trotzdem mal offen, vielleicht lässt sich durch ein bisschen Optimierung zumindest die Wahrscheinlichkeit reduzieren, dass wir in irgendwelche Timeouts des Hook-Mechanismus laufen.

**Comment by andypillip** [comment]
Cool danke für die schnelle Antwort.

Es ist gerade wieder passiert, und mit Alt hat es sich gelöst. Ich bin aber wieder auf das Touchpad gekommen.

Kann es sein, dass eine Touchpad-Berührung während des Drückens von Alt das Keyup-Event ebenfalls verhindert? Ich schau' mal ob ich das Touchpad deaktivieren kann während ich tippe.

**Comment by Rojetto** [comment]
Puh, grundsätzlich kann der Touchpad-Treiber sicher beliebigen Unsinn machen. Bei mir passiert auf jeden Fall nichts in der Richtung. Wäre gut, wenn du es reproduzieren kannst.

**Comment by Rojetto** [comment]
Schließe hier erstmal. Wenn das Problem reproduzierbar weiter auftritt, bitte melden.
