### ISSUE TITLE
Funktioniert nicht auf Windows 10 mit kbdneo

### ISSUE THREAD

**Issue by Isopod** [Rojetto/ReNeo#84]
Ich benutze seit geraumer Zeit den nativen kbdneo-Treiber mit der AHK-Erweiterung unter Windows. Ich würde gerne die AHK-Erweiterung hiermit ersetzen, aber leider hatte ich damit bis jetzt kein Glück. Egal welches Layout ich einstelle, es scheint einfach keine Wirkung zu haben. Wichtig wäre mir vor allem Ebene 4 unter Neo (Pfeiltasten und Escape).

Hier meine Liste an Tastaturlayouts:
![image](https://user-images.githubusercontent.com/2358109/150376450-a50d6ddb-31a2-489a-8ab2-1c3cbd352815.png)

Hier das Log:
 ```
Starting ReNeo...
WARNING: File logging enabled, make sure you know what you're doing!
Initializing keysyms from C:\Users\isopod\ReNeo\keysymdef.h
Initializing compose
Removing compose module C:\Users\isopod\ReNeo\compose\base.remove
Removing compose module C:\Users\isopod\ReNeo\compose\cyrillic.remove
Removing compose module C:\Users\isopod\ReNeo\compose\diacritics.remove
Removing compose module C:\Users\isopod\ReNeo\compose\greek-oxia.remove
Removing compose module C:\Users\isopod\ReNeo\compose\greek.remove
Removing compose module C:\Users\isopod\ReNeo\compose\lang.remove
Removing compose module C:\Users\isopod\ReNeo\compose\math-font.remove
Removing compose module C:\Users\isopod\ReNeo\compose\math.remove
Removing compose module C:\Users\isopod\ReNeo\compose\unicode.remove
Loading compose module C:\Users\isopod\ReNeo\compose\base.module
Loading compose module C:\Users\isopod\ReNeo\compose\cyrillic.module
Loading compose module C:\Users\isopod\ReNeo\compose\diacritics.module
Loading compose module C:\Users\isopod\ReNeo\compose\en_US.module
Loading compose module C:\Users\isopod\ReNeo\compose\greek-oxia.module
Loading compose module C:\Users\isopod\ReNeo\compose\greek.module
Loading compose module C:\Users\isopod\ReNeo\compose\klingon-kp.module
Loading compose module C:\Users\isopod\ReNeo\compose\klingon.module
Loading compose module C:\Users\isopod\ReNeo\compose\lang.module
Loading compose module C:\Users\isopod\ReNeo\compose\math-font.module
Loading compose module C:\Users\isopod\ReNeo\compose\math.module
Time spent reading and parsing module files: 157 ms
Loaded 24989 compose sequences.
Initialization complete!
Foreground window hook active!
Running with PerMonitorV2 DPI scaling
Keyboard hook active
Keyboard hook registered!
Updating keyboard layout
Found input locale FFFFFFFFF0C02000
Input locale corresponds to dll file name 'kbdneo2.dll'
Changing keyboard layout to Neo
Changed to window with title 'ReNeo'
Changed to window with title 'C:\Users\isopod\ReNeo\reneo_debug.exe'
Changed to window with title '*Untitled - Notepad'
Updating keyboard layout
Found input locale FFFFFFFFF0C02000
Input locale corresponds to dll file name 'kbdneo2.dll'
(injected) (down)             | Scan 0x0056 | VK_OEM_8 (0xDF)
(injected) (down)             | Scan 0x001F | VK_KEY_I (0x49)
(injected)  (up)              | Scan 0x001F | VK_KEY_I (0x49)
(injected) (down)             | Scan 0x001F | VK_KEY_I (0x49)
(injected)  (up)              | Scan 0x001F | VK_KEY_I (0x49)
(injected) (down)             | Scan 0x001F | VK_KEY_I (0x49)
(injected)  (up)              | Scan 0x001F | VK_KEY_I (0x49)
(injected) (down)             | Scan 0x0021 | VK_KEY_E (0x45)
(injected)  (up)              | Scan 0x0021 | VK_KEY_E (0x45)
(injected) (down)             | Scan 0x0021 | VK_KEY_E (0x45)
(injected)  (up)              | Scan 0x0021 | VK_KEY_E (0x45)
(injected) (down)             | Scan 0x0021 | VK_KEY_E (0x45)
(injected)  (up)              | Scan 0x0021 | VK_KEY_E (0x45)
(injected)  (up)              | Scan 0x0056 | VK_OEM_8 (0xDF)
Changed to window with title 'C:\Users\isopod\ReNeo\reneo_debug.exe'
```

Das war der Versuch, die Pfeiltasten (←, →) auf Ebene 4 zu benutzen. Passiert ist stattdessen nichts.

**Comment by Rojetto** [comment]
Danke für die Meldung und den Log. In Letzterem sieht es für mich so aus, als bekommt ReNeo überhaupt keine physischen Tastatur-Events zu sehen und macht dementsprechend nichts. Alle Events im Log sind mit `injected` markiert, kommen also nicht direkt von der Tastatur sondern von irgendeiner anderen Software.

Hast du außer ReNeo irgendwelche anderen Tastaturtools oder alte AHK-Skripte laufen? ReNeo sollte idealerweise das einzige Tool sein, das Tastaturevents anfasst.

**Comment by Isopod** [comment]
Hallo, ja, das stimmt. Der Input kommt von einer selbstgeschriebenen Software ähnlich wie Synergy. Mit dem AHK-Skript hatte ich aber nie dieses Problem. AHK muss also irgendetwas anders machen. Würde es etwas kaputt machen, wenn injizierte Events nicht ignoriert würden?

**Comment by Rojetto** [comment]
Die von dir verlinkte Zeile einfach zu entfernen würde im Allgemeinen nicht funktionieren, da ReNeo dann anfängt die selbst erzeugten Events wieder als neue Eingaben zu verarbeiten. Im alten AHK-Skript ist das kein Problem, weil dort Eingabeevents (Mod4+Buchstaben) und Ausgabeevents (Pfeiltasten, Enter, Esc, ...) disjunkt sind.

Für diesen spezifischen Fall (Erweiterungsmodus, Ebene 4 so belegt wie sie ist) habe ich es trotzdem kurz probiert, da wie beim alten AHK-Skript zumindest kein totales Chaos entstehen sollte. Folgende Dinge sind mir aufgefallen:
- normal Tippen geht natürlich, auch Ebene 3, 5, 6
- Pfeiltasten, Enter, Escape auf Ebene 4 geht
- Nummernblock auf Ebene 4 geht *nicht*, dort werden die erzeugten Nummernblock-Events nochmal konvertiert in Pfeiltasten o.ä.
- Capslock mit Doppel-Shift geht *nicht*

Das Problem mit dem Nummernblock ließ sich durch Anpassen des Layouts lösen.

Eine entsprechend gepatchte Version [habe ich hochgeladen](https://github.com/Rojetto/ReNeo/releases/tag/v1.5.4-all-events), die Anpassungen [liegen in einem separaten Zweig](https://github.com/Rojetto/ReNeo/tree/special_all_events). Kannst dich gerne melden, ob es damit funktioniert.

**Comment by Isopod** [comment]
Vielen Dank für die schnelle Reaktion. Habe es gerade getestet und es funktioniert. Für mich ist das Problem damit gelöst.
