### ISSUE TITLE
Mod4-Lock per Option abschaltbar

### ISSUE THREAD

**Issue by KL-Sven** [Rojetto/ReNeo#86]
Mir passiert es häufig, dass ich aus Versehen Mod4-Lock aktiviere. Absichtlich möchte ich mit Ausnahme von Mod1 keine Locks aktivieren. Ich würde die Funktion daher gerne abschalten können.

Vielleicht gibt es ja auch Nutzer, denen das auch häufig passiert, aber die Funktion gerne hätten. Dann könnte man evtl. das Timing optimieren. Soll heißen, man müsste die beiden Mods etwas länger drücken. Könnte dann natürlich für andere zu langsam sein.

**Comment by kaimi** [comment]
Ich habe lustigerweise das gleiche Problem, und ich habe nur _eine_ Mod4 :)

Dummerweise passiert das normalerweise beim Zocken, und außer „ASAP ReNeo neu starten“ habe ich dann keine Zeit zum Troubleshooten.

**Comment by KL-Sven** [comment]
Nur 1 Mod4? Alt-Gr abgeschraubt, oder wie darf ich mir das vorstellen?

**Comment by kaimi** [comment]
So :) https://github.com/kaimi/tmk_keyboard

**Comment by Rojetto** [comment]
Habe eine Config-Option `"enableMod4Lock"` hinzugefügt. Kann im nächsten Release genutzt werden.
