### ISSUE TITLE
Switch "cmd" and "option" - Magic keyboard

### ISSUE THREAD

**Issue by kobold2301** [Rojetto/ReNeo#88]
Hallo,
erst mal danke für das Projekt.

Ich nutze seit kurzem eine "Magic Keyboard" am PC, leider ist dort unter dem Neo-Standard-Layout. Die "Command-R"-Taste -> "Windows"-Taste und "option-R" der RMod4, gerne würde ich dies tauschen. Mithilfe der Dokumentation in "DEVDOC.md", hätte ich gedacht, dass ich bei den "modifiers" nur "38+": "RMod4" durch "5C": "RMod4" ersetzten muss und irgendwie das "38+" auf Windows-Funktion, leider hat beides nicht funktioniert.

Muss ich diese Windows-Funktion vorher herausfiltern?

Ein kleiner Hinweis was genau ich falsch gemacht hätte, wäre nett.

Viele Grüße

**Comment by Rojetto** [comment]
Grundsätzlich klingt die Idee richtig. Nach meiner Recherche ist der Scancode für die „Command-R“-Taste `5C+` (das Plus signalisiert das Extended-Bit). Unter `"modifiers"` müsstest du dann also `"38+": "RMod4"` ersetzen mit `"5C+": "RMod4"`.

Warum das Umlegen der Windows-Funktion auf „Option-R“ nicht geht, kann ich gerade nicht nachvollziehen. In meinen Tests funktioniert es, wenn man das Layout mit diesem Eintrag erweitert:
```
"38+": [{"vk": "VK_RWIN"}, {"vk": "VK_RWIN"}, {"vk": "VK_RWIN"}, {"vk": "VK_RWIN"}, {"vk": "VK_RWIN"}, {"vk": "VK_RWIN"}],
```

Falls es damit immer noch Probleme gibt, müssten wir uns den Log anschauen. Dazu das unmodifizierte Layout wiederherstellen, ReNeo beenden und stattdessen `reneo_debug.exe` starten, einmal Command-R und dann Option-R drücken, ReNeo wieder beenden und die Logdatei `reneo_log.txt` hier einfügen.

**Comment by kobold2301** [comment]
Vielen Danke!
Mit den von Ihnen erwähnten erweiterten Eintrag haben sich fast alle Problem mit der Windowstaste gelöst, nur für die Kombination "RMod4" + "G" musste ich noch die  XboxGameBar ausschalten  (Einstellungen ->Spiele ).
